### PR TITLE
GitHub Action: Test and Lint

### PR DESCRIPTION
**Pull request by brisberg**
Added workflow yaml for GitHub Action for testing and linting on push.

Not sure if you have used GitHub Actions for CI before, but they added free runners for them last year and have been building a repository of actions for normal CI tasks.

Once this is merged, it will run `yarn test` and `yarn run lint` on the latest commit for each Pull Request. It will post the results in the PR near the bottom. This will help to enforce contributors keeping the tests and lint passing.

These CI jobs are free for public repos, read more here: https://github.com/features/actions

### CODE REVIEW

**Comment by brisberg** [comment]
Not sure if you can view Action logs on my fork, but here is the run for this branch:

https://github.com/brisberg/screeps-server-mockup/runs/478686914

**Comment by brisberg** [comment]
Does that mean you are on board with using Github Actions?

**Comment by pyrodogg** [comment]
Yea looks nice. I have some small experience with Gitlab CI, first with
GitHub Actions

**Comment by brisberg** [comment]
Cool, yeah it is very similar to Gitlab CI

**Pull request merged**
